spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/mall_sms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon
mybatis-plus:
  #自增主键,在table注解里
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000





