server:
  port: 13000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/mall_oms?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: mall-coupon

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
